language: java
jdk:
  - openjdk8

install: sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install maven

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - gelosofederico@gmail.com
      - joacoelordi@gmail.com
      - crist.torales@gmail.com
      - cristinaa.kuo@gmail.com
    on_failure: always