language: java
jdk:
  - openjdk8

install: maven

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - maven

script:
  - mvn package

notifications:
  email:
    recipients:
      - gelosofederico@gmail.com
    on_failure: always